image: node:6

pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - cp -r static/.well-known public/
  - cp -r static/robots.txt public/
  artifacts:
    paths:
    - public
  only:
  - master
